# Generated by Django 6.1 on 2026-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Опыт работы в годах'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialists/'),
        ),
    ]
