# Generated by Django 6.1 on 2026-09-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options'),
        ('services', '0002_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='С какого дня')),
                ('end_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='По какой день')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('specialist', 'date', 'time'), name='unique_specialist_booking'),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='services.specialist'),
        ),
    ]
