# Generated by Django 6.1 on 2026-09-03 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_status'),
        ('services', '0002_specialist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_specialist_booking',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('specialist', 'date', 'time'), name='unique_scheduled_specialist_booking'),
        ),
    ]
