# Generated by Django 6.1 on 2026-10-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_unique_specialist_booking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Запись клиента', 'verbose_name_plural': 'Записи клиентов'},
        ),
        migrations.AlterModelOptions(
            name='workinghour',
            options={'verbose_name': 'Рабочее время', 'verbose_name_plural': 'Рабочее время'},
        ),
    ]
